# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='epit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Epitet',
        ),
    ]
